controllers:
  - setpointTopic: "testSetpointTopic0"
    feedbackTopic: "testFeedbackTopic0"
    outputTopic: "testOutputTopic0"
    P: 10
    I: 2 #1.5
    D: 0 #0.5557 #0.005

  # - setpointTopic: "testSetpointTopic1"
  #   feedbackTopic: "testFeedbackTopic1"
  #   outputTopic: "testOutputTopic1"
  #   P: 4.5
  #   I: 2.5
  #   D: 1.5