controllers:
  - setpointTopic: "testSetpointTopic0"
    feedbackTopic: "testFeedbackTopic0"
    outputTopic: "testOutputTopic0"
    P: 9
    I: 1.5 
    D: 0
    min: -100
    max: 100

  # - setpointTopic: "testSetpointTopic1"
  #   feedbackTopic: "testFeedbackTopic1"
  #   outputTopic: "testOutputTopic1"
  #   P: 4.5
  #   I: 2.5
  #   D: 1.5